---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: Install python3
      raw: dnf -y update && dnf install -y python3
      become: true
    - name: Gather facts
      setup:

- name: Docker installation
# when: ansible_distribution == 'Red Hat Enterprise Linux'
  hosts: all
  roles:
    - docker
  
